#include <stdio.h>
#include "bytecode.h"

// -- Bytecode generator --

static ByteCodeResult EmitGeneratorError(const char* message) {
    ByteCodeResult result = {
        .type = BYTECODE_GENERATE_ERROR,
        .as.error = {
            .message = MakeString(message),
            .token = NULL,
        }
    };
    return result;
}

ByteCodeResult GenerateByteCode(Ast* ast, Allocator* allocator) {
    return EmitGeneratorError("Not implemented"); 
}

// -- Printing --

const char* MapOpCodeToStr(OpCode code) {
    switch (code) {
        case OP_NIL: return "OP_NIL";
        default: return NULL;
    }
}

const char* MapByteCodeResultTypeToStr(ByteCodeResultType type) {
    switch(type) {
        case BYTECODE_GENERATE_SUCCESS: return "BYTECODE_GENERATE_SUCCESS";
        case BYTECODE_GENERATE_ERROR: return "BYTECODE_GENERATE_ERROR";
        default: return NULL;
    }
}

void PrintByteCodeResult(ByteCodeResult result) {
    if (result.type == BYTECODE_GENERATE_ERROR) {
        ByteCodeGenerateError error = result.as.error;
        fprintf(stderr, "Byte code generator error: ");
        PrintStringErr(error.message);
        fprintf(stderr, "\n");

        if (error.token != NULL) {
            PrintToken(*(error.token));
        }
        return;
    }
    printf("Generated bytecode successfully\n");
}
